# Generated by Django 6.0.3 on 2026-03-27 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctors", "0002_blockedslot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        default="offline",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("approved", "Tasdiqlangan"),
                            ("rejected", "Rad etilgan"),
                            ("cancelled", "Bekor qilingan"),
                            ("completed", "Yakunlangan"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Bemor murojaat sababi"),
                ),
                (
                    "reject_reason",
                    models.TextField(blank=True, help_text="Rad etish sababi"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Doctor izohlari (uchrashuv paytida)"
                    ),
                ),
                ("room_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_appointments",
                        to="doctors.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-start_time"],
                "indexes": [
                    models.Index(
                        fields=["patient", "status"],
                        name="meetings_ap_patient_fc4a38_idx",
                    ),
                    models.Index(
                        fields=["doctor", "status"],
                        name="meetings_ap_doctor__bb95e0_idx",
                    ),
                    models.Index(
                        fields=["doctor", "date"], name="meetings_ap_doctor__04fcd6_idx"
                    ),
                    models.Index(
                        fields=["status", "date"], name="meetings_ap_status_a67400_idx"
                    ),
                ],
            },
        ),
    ]
