# Generated by Django 6.0.3 on 2026-04-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancelled_by",
            field=models.CharField(
                blank=True,
                help_text="Bekor qilgan tomon: patient, doctor, admin",
                max_length=10,
            ),
        ),
    ]
