# Generated by Django 5.2.13 on 2026-05-04 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_appointment_cancelled_by'),
        ('users', '0008_backfill_patient_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patient'),
        ),
    ]
