# Generated by Django 5.2.13 on 2026-08-05 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_doctorprofile_consultation_duration_min_and_more'),
        ('meetings', '0004_backfill_appointment_patient_profile'),
        ('payments', '0018_alter_payment_purpose'),
        ('users', '0009_alter_user_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending_payment', "To'lov kutilmoqda"), ('confirmed', 'Tasdiqlangan'), ('completed', 'Yakunlangan'), ('cancelled_by_patient', 'Bemor bekor qildi'), ('cancelled_by_doctor', 'Shifokor bekor qildi'), ('expired', "To'lanmay muddati o'tdi")], default='pending_payment', max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('room_name', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.CharField(blank=True, help_text='Bekor qilgan tomon: patient, doctor, admin', max_length=10)),
                ('cancel_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_consultations', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_consultations', to=settings.AUTH_USER_MODEL)),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='users.patient')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='payments.payment')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['patient', 'status'], name='meetings_co_patient_cd68ac_idx'), models.Index(fields=['doctor', 'status'], name='meetings_co_doctor__d5dde8_idx'), models.Index(fields=['doctor', 'date'], name='meetings_co_doctor__b2083f_idx'), models.Index(fields=['status', 'created_at'], name='meetings_co_status_d913c8_idx')],
            },
        ),
    ]
