# Generated by Django 6.0.3 on 2026-04-07 08:29

from django.db import migrations
from collections import defaultdict


def merge_duplicate_rooms(apps, schema_editor):
    """Bir juftlik (patient, doctor) uchun bir nechta room bo'lsa, eng eskisiga
    barcha xabarlarni ko'chirib qolganlarini o'chiradi."""
    ChatRoom = apps.get_model("chat", "ChatRoom")
    Message = apps.get_model("chat", "Message")

    groups = defaultdict(list)
    for room in ChatRoom.objects.all().prefetch_related("participants"):
        ids = tuple(sorted(room.participants.values_list("id", flat=True)))
        if not ids:
            continue
        groups[ids].append(room)

    for ids, rooms in groups.items():
        if len(rooms) <= 1:
            continue
        rooms.sort(key=lambda r: r.created_at)
        primary = rooms[0]
        for dup in rooms[1:]:
            Message.objects.filter(room=dup).update(room=primary)
            dup.delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_rooms, noop),
        migrations.RemoveField(
            model_name="chatroom",
            name="appointment",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="room_type",
        ),
    ]
