# Generated by Django 6.0.3 on 2026-04-10 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_remove_chatroom_appointment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[("video", "Video"), ("audio", "Audio")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ringing", "Jiringlamoqda"),
                            ("active", "Faol"),
                            ("completed", "Tugallangan"),
                            ("missed", "Javobsiz"),
                            ("rejected", "Rad etilgan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="ringing",
                        max_length=10,
                    ),
                ),
                ("room_name", models.CharField(max_length=100)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration",
                    models.PositiveIntegerField(default=0, help_text="Soniyalarda"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "callee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "caller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_sessions",
                        to="chat.chatroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "-created_at"],
                        name="chat_callse_room_id_6489e1_idx",
                    ),
                    models.Index(
                        fields=["callee", "status"],
                        name="chat_callse_callee__cf3d0e_idx",
                    ),
                ],
            },
        ),
    ]
