# Generated by Django 6.0.3 on 2026-04-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_callsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("consultation", "Konsultatsiya"),
                    ("support", "Qo'llab-quvvatlash"),
                ],
                default="consultation",
                max_length=15,
            ),
        ),
    ]
