# Generated by Django 5.2.13 on 2026-05-04 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_room_type'),
        ('doctors', '0008_remove_legacy_schedule'),
        ('users', '0008_backfill_patient_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='callee_scope',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], help_text="Callee'ning kutilgan rol-konteksti (xona turidan kelib chiqib).", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='caller_scope',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], help_text="Caller JWT scope'i (qo'ng'iroq qilgandagi rol)", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='users.patient'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_scope',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], help_text="Yuborish paytida user'ning JWT scope'i (Yandex Taxi modeli).", max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['patient', 'doctor'], name='chat_chatro_patient_3dd504_idx'),
        ),
    ]
