# Generated by Django 5.2.13 on 2026-05-04 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_backfill_chat_role_context'),
        ('doctors', '0008_remove_legacy_schedule'),
        ('users', '0008_backfill_patient_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('doctor__isnull', False), ('patient__isnull', False)), fields=('patient', 'doctor'), name='unique_consultation_room_per_patient_doctor'),
        ),
    ]
