# Generated by Django 5.2.13 on 2026-05-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_unique_consultation_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_scope',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], help_text="Yuborish paytida user'ning JWT scope'i.", max_length=10, null=True),
        ),
    ]
