# Generated by Django 5.2.13 on 2026-06-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='ringing_at',
            field=models.DateTimeField(blank=True, help_text="Callee qurilmasi incoming UI ko'rsatgani (delivery ack) vaqti", null=True),
        ),
    ]
