# Generated by Django 5.2.13 on 2026-06-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_message_audio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='transcript',
            field=models.TextField(blank=True, help_text='Ovozli xabar STT transkripti (Gemini, on-demand).'),
        ),
        migrations.AddField(
            model_name='message',
            name='transcript_status',
            field=models.CharField(blank=True, choices=[('pending', 'Transkripsiya qilinmoqda'), ('ready', 'Tayyor'), ('failed', 'Xato')], help_text="STT holati. null = hali so'ralmagan.", max_length=10, null=True),
        ),
    ]
