# Generated by Django 5.2.13 on 2026-06-25 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_message_transcript_message_transcript_status'),
        ('doctors', '0012_cleanup_orphan_doctorpatient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_ai',
            field=models.BooleanField(default=False, help_text='AI yordamchi yuborgan avto-javob (sender doctor, lekin AI).'),
        ),
        migrations.CreateModel(
            name='ChatAIDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('replies_count', models.PositiveIntegerField(default=0)),
                ('tokens_input', models.PositiveIntegerField(default=0)),
                ('tokens_output', models.PositiveIntegerField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_ai_usage', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'doctor', 'date'], name='chat_chatai_patient_839976_idx')],
                'unique_together': {('patient', 'doctor', 'date')},
            },
        ),
    ]
