# Generated by Django 5.2.13 on 2026-08-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_message_is_ai_chataidailyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='doctor_visible_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
