# Generated by Django 5.2.13 on 2026-07-30 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(db_index=True, max_length=40)),
                ('scope', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(db_index=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature usage (daily)',
                'indexes': [models.Index(fields=['feature', 'date'], name='analytics_f_feature_3abc3e_idx'), models.Index(fields=['user', '-date'], name='analytics_f_user_id_720f63_idx'), models.Index(fields=['date'], name='analytics_f_date_42c36d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'feature', 'date'), name='uniq_feature_usage_user_feature_date')],
            },
        ),
    ]
