# Generated by Django 5.2.13 on 2026-05-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='feedbacks_r_doctor__c8bbee_idx',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_hidden',
        ),
    ]
