# Generated by Django 5.2.13 on 2026-05-04 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_remove_review_feedbacks_r_doctor__c8bbee_idx_and_more'),
        ('users', '0008_backfill_patient_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.patient'),
        ),
    ]
