# Generated by Django 5.2.13 on 2026-05-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_review_is_edited_review_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label_uz', models.CharField(max_length=80)),
                ('label_ru', models.CharField(blank=True, max_length=80)),
                ('sentiment', models.CharField(choices=[('positive', 'Ijobiy'), ('negative', 'Salbiy')], max_length=10)),
                ('icon', models.CharField(blank=True, help_text='Emoji yoki belgi', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sentiment', 'order', 'id'],
                'indexes': [models.Index(fields=['sentiment', 'is_active'], name='feedbacks_r_sentime_a46f9b_idx')],
            },
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='feedbacks.reviewtag'),
        ),
    ]
