# Generated by Django 6.0.3 on 2026-03-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("code", models.CharField(max_length=10)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("register", "Register"), ("login", "Login")],
                        max_length=10,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("role", models.CharField(blank=True, max_length=10)),
                ("telegram_chat_id", models.BigIntegerField(blank=True, null=True)),
                ("is_used", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
