# Generated by Django 5.2.13 on 2026-05-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_otpcode_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
