# Generated by Django 5.2.13 on 2026-06-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_add_otp_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='sex',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
