# Generated by Django 5.2.13 on 2026-06-16 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0012_cleanup_orphan_doctorpatient'),
        ('users', '0009_alter_user_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('uz-cyrl', 'Ўзбек'), ('ru', 'Русский')], default='uz', max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations_about', to=settings.AUTH_USER_MODEL)),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='users.patient')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIHealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='Hisobot kuni')),
                ('period_end', models.DateField(help_text='Tahlil oynasi oxiri')),
                ('summary', models.TextField(blank=True, help_text='AI umumiy insight (2-4 jumla)')),
                ('detected_changes', models.JSONField(blank=True, default=list, help_text="Aniqlangan o'zgarishlar/insightlar ro'yxati")),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('attention', "E'tibor talab"), ('critical', 'Jiddiy')], default='normal', max_length=16)),
                ('tokens_input', models.PositiveIntegerField(default=0)),
                ('tokens_output', models.PositiveIntegerField(default=0)),
                ('seen_at', models.DateTimeField(blank=True, help_text="Doctor o'qigan vaqt", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_health_reports', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_health_reports', to=settings.AUTH_USER_MODEL)),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_health_reports', to='users.patient')),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('tokens_input', models.PositiveIntegerField(default=0)),
                ('tokens_output', models.PositiveIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='health_ai.aiconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['doctor_profile', 'patient_profile', '-updated_at'], name='health_ai_a_doctor__5b2549_idx'),
        ),
        migrations.AddIndex(
            model_name='aihealthreport',
            index=models.Index(fields=['doctor', '-period_start'], name='health_ai_a_doctor__2cf807_idx'),
        ),
        migrations.AddIndex(
            model_name='aihealthreport',
            index=models.Index(fields=['doctor', 'severity', '-period_start'], name='health_ai_a_doctor__c9d70f_idx'),
        ),
        migrations.AddConstraint(
            model_name='aihealthreport',
            constraint=models.UniqueConstraint(fields=('patient_profile', 'doctor', 'period_start'), name='uniq_daily_ai_report'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='health_ai_a_convers_cc3278_idx'),
        ),
    ]
