# Generated by Django 5.2.13 on 2026-05-12 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('drug', 'Dori vositasi'), ('substance', 'Substansiya'), ('in_vivo', 'In vivo diagnostika'), ('med_device', 'Tibbiy texnika'), ('in_vitro', 'In vitro diagnostika')], db_index=True, max_length=20)),
                ('name', models.TextField(db_index=True, help_text="Savdo nomi (Kirill + Lotin birga, ro'yxatdagidek)")),
                ('name_normalized', models.TextField(blank=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Annulirovannye (bekor qilingan) yozuvlar uchun False')),
                ('source', models.CharField(choices=[('import', "Excel'dan import"), ('manual', "Admin qo'lda kiritgan")], default='import', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='pharmacy_dr_categor_62d823_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='pharmacy_drug_uniq_cat_name')],
            },
        ),
        migrations.CreateModel(
            name='DrugImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('drug', 'Dori vositasi'), ('substance', 'Substansiya'), ('in_vivo', 'In vivo diagnostika'), ('med_device', 'Tibbiy texnika'), ('in_vitro', 'In vitro diagnostika')], max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('is_active_default', models.BooleanField(default=True, help_text="Annulled fayl bo'lsa False — yozuvlar is_active=False yaratiladi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
