# Generated by Django 6.0.3 on 2026-03-26 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("medication", "Dori"),
                            ("exercise", "Mashq"),
                            ("diet", "Parhez"),
                            ("water", "Suv ichish"),
                            ("sleep", "Uyqu"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("dosage", models.CharField(blank=True, max_length=100)),
                ("duration", models.CharField(blank=True, max_length=100)),
                ("time", models.TimeField()),
                (
                    "repeat",
                    models.CharField(
                        choices=[
                            ("daily", "Har kuni"),
                            ("every_other_day", "Har ikki kuni"),
                            ("three_times_week", "Har uch kuni"),
                            ("weekly", "Haftalik"),
                            ("biweekly", "Har ikki haftada"),
                            ("monthly", "Oylik"),
                            ("custom", "Maxsus"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["time"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Bajarildi"),
                            ("skipped", "O'tkazib yuborildi"),
                        ],
                        max_length=10,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="treatment.treatment",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("treatment", "date")},
            },
        ),
    ]
