# Generated by Django 6.0.3 on 2026-03-26 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="treatment",
            index=models.Index(
                fields=["user", "is_active"], name="treatment_t_user_id_b1f7df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatment",
            index=models.Index(
                fields=["user", "time"], name="treatment_t_user_id_7ee6d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatmentlog",
            index=models.Index(
                fields=["treatment", "date", "status"],
                name="treatment_t_treatme_ef84d1_idx",
            ),
        ),
    ]
