# Generated by Django 6.0.3 on 2026-03-27 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0002_treatment_treatment_t_user_id_b1f7df_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Doctor yozgan bo'lsa — doctor user, patient o'zi qo'shgan bo'lsa null",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescribed_treatments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DailyCalorieLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calories",
                    models.PositiveIntegerField(
                        help_text="Kunlik kaloriya chegarasi (kcal)"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Doctor izohi")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calorie_limit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="set_calorie_limits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
