# Generated by Django 6.0.3 on 2026-03-30 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0003_treatment_created_by_dailycalorielimit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="treatment",
            name="treatment_t_user_id_b1f7df_idx",
        ),
        migrations.AddField(
            model_name="treatment",
            name="custom_days",
            field=models.CharField(
                blank=True,
                help_text="repeat=custom bo'lsa hafta kunlari: '1,3,5' (1=Du, 7=Ya)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Muolaja tugash sanasi. Null = cheksiz.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Oxirgi qabul vaqti. interval_hours bilan ishlatiladi.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="interval_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Har necha soatda (masalan 2 = har 2 soatda). time dan end_time gacha.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Faol"),
                    ("paused", "To'xtatilgan"),
                    ("completed", "Tugallangan"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="time",
            field=models.TimeField(
                blank=True,
                help_text="Birinchi qabul vaqti. interval_hours bo'lsa boshlanish vaqti.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="treatment",
            index=models.Index(
                fields=["user", "status"], name="treatment_t_user_id_501d45_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="is_active",
        ),
    ]
