# Generated by Django 6.0.3 on 2026-04-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0004_remove_treatment_treatment_t_user_id_b1f7df_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycalorielimit",
            name="carbs_limit",
            field=models.PositiveIntegerField(
                blank=True, help_text="Kunlik uglevod chegarasi (g)", null=True
            ),
        ),
        migrations.AddField(
            model_name="dailycalorielimit",
            name="fat_limit",
            field=models.PositiveIntegerField(
                blank=True, help_text="Kunlik yog' chegarasi (g)", null=True
            ),
        ),
        migrations.AddField(
            model_name="dailycalorielimit",
            name="protein_limit",
            field=models.PositiveIntegerField(
                blank=True, help_text="Kunlik oqsil chegarasi (g)", null=True
            ),
        ),
    ]
