# Generated by Django 5.2.13 on 2026-05-04 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_dailycalorielimit_carbs_limit_and_more'),
        ('users', '0008_backfill_patient_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycalorielimit',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calorie_limits', to='users.patient'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='users.patient'),
        ),
    ]
