# Generated by Django 5.2.13 on 2026-05-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_backfill_doctorpatient_patient_profile'),
        ('treatment', '0007_backfill_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycalorielimit',
            name='doctor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_calorie_limits', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='doctor_profile',
            field=models.ForeignKey(blank=True, help_text="Treatment'ni yozgan doctor (patient self-add bo'lsa null).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_treatments', to='doctors.doctorprofile'),
        ),
    ]
