# Generated by Django 5.2.13 on 2026-05-16 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_denormalized_fields(apps, schema_editor):
    """Mavjud loglarga user/title/type ni Treatment'dan to'ldirish."""
    TreatmentLog = apps.get_model("treatment", "TreatmentLog")
    for log in TreatmentLog.objects.select_related("treatment").iterator():
        if log.treatment_id:
            log.user_id = log.treatment.user_id
            log.treatment_title = log.treatment.title
            log.treatment_type = log.treatment.type
            log.save(update_fields=["user", "treatment_title", "treatment_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0009_backfill_doctor_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentlog',
            name='treatment_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='treatmentlog',
            name='treatment_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='treatmentlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treatmentlog',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='treatment.treatment'),
        ),
        migrations.AddIndex(
            model_name='treatmentlog',
            index=models.Index(fields=['user', 'date', 'status'], name='treatment_t_user_id_7ae3f0_idx'),
        ),
        migrations.RunPython(backfill_denormalized_fields, migrations.RunPython.noop),
    ]
