# Generated by Django 5.2.13 on 2026-05-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0010_treatmentlog_treatment_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='notes',
            field=models.TextField(blank=True, help_text="Eslatmalar (ixtiyoriy) — qo'shimcha ko'rsatmalar."),
        ),
    ]
