# Generated by Django 5.2.13 on 2026-06-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0011_treatment_notes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='treatmentlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='treatment',
            name='as_needed_reason',
            field=models.TextField(blank=True, help_text="Qaysi holatda ichish (masalan 'Harorat 38° dan oshganda'). Faqat is_as_needed=True da mazmunli."),
        ),
        migrations.AddField(
            model_name='treatment',
            name='is_as_needed',
            field=models.BooleanField(default=False, help_text="True = ehtiyoj bo'lganda ichiladi (jadval/eslatma yo'q)."),
        ),
        migrations.AddField(
            model_name='treatment',
            name='max_per_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Xavfsizlik chegarasi: kuniga eng ko'pi bilan necha marta.", null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='min_interval_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Xavfsizlik chegarasi: qabullar orasida kamida soat.', null=True),
        ),
    ]
