# Generated by Django 5.2.13 on 2026-06-27 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0012_alter_treatmentlog_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='times',
            field=models.JSONField(blank=True, default=list, help_text='Aniq qabul vaqtlari ro\'yxati: ["08:00:00", ...]. Multi-slot uchun.'),
        ),
        migrations.AddField(
            model_name='treatmentlog',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='treatmentlog',
            constraint=models.UniqueConstraint(condition=models.Q(('scheduled_for__isnull', False)), fields=('treatment', 'scheduled_for'), name='uniq_treatment_scheduled_slot'),
        ),
    ]
