# Generated by Django 5.2.13 on 2026-08-15 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0013_treatment_times_treatmentlog_scheduled_for_and_more'),
        ('users', '0009_alter_user_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_key', models.CharField(help_text="DO Spaces'dagi rasm kaliti", max_length=500)),
                ('status', models.CharField(choices=[('pending_review', 'Tasdiqlash kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('discarded', 'Rad etilgan')], default='pending_review', max_length=20)),
                ('summary', models.TextField(blank=True, help_text="AI qisqacha izohi (qog'ozda nima yozilgani)")),
                ('ai_items', models.JSONField(blank=True, default=list, help_text='AI taklif qilgan muolajalar [{title, type, dosage, times, repeat, ...}]')),
                ('ai_warnings', models.JSONField(blank=True, default=list, help_text="O'qib bo'lmagan/noaniq joylar haqida ogohlantirishlar")),
                ('created_treatment_ids', models.JSONField(blank=True, default=list, help_text="Tasdiqlangach yaratilgan Treatment id'lari")),
                ('tokens_input', models.PositiveIntegerField(default=0)),
                ('tokens_output', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_scans', to='users.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='treatment_p_user_id_582eec_idx')],
            },
        ),
    ]
