# Generated by Django 5.2.13 on 2026-08-15 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_alter_user_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('child', 'Farzand'), ('parent', 'Ota-ona'), ('spouse', "Turmush o'rtog'i"), ('sibling', 'Aka-uka / opa-singil'), ('other', 'Boshqa')], default='other', help_text="A'zoning bemorga nisbatan kimligi (bemor belgilaydi)", max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('declined', 'Rad etilgan'), ('revoked', 'Bekor qilingan')], default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to=settings.AUTH_USER_MODEL)),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to='users.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', 'status'], name='family_fami_member__c02160_idx'), models.Index(fields=['patient', 'status'], name='family_fami_patient_106e0a_idx')],
                'constraints': [models.UniqueConstraint(fields=('patient', 'member'), name='uniq_family_link')],
            },
        ),
    ]
