# Generated by Django 6.0.3 on 2026-04-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("doctor", "Doctor"),
                    ("admin", "Admin"),
                ],
                default="patient",
                help_text="Hozir qaysi sifatida ishlayapti (switch qilinadi)",
                max_length=10,
            ),
        ),
    ]
