# Generated by Django 5.2.13 on 2026-08-15 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_alter_user_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITrackingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='Hisobot qamrab olgan kun (boshlanishi)')),
                ('period_end', models.DateField(help_text='Hisobot qamrab olgan kun (tugashi)')),
                ('summary', models.TextField(help_text='AI xulosasi — bemorga tushunarli tilda')),
                ('detected_changes', models.JSONField(blank=True, default=list, help_text="Aniqlangan o'zgarishlar ro'yxati [{title, description, severity}]")),
                ('recommendations', models.JSONField(blank=True, default=list, help_text="Bemorga umumiy tavsiyalar (tashxis/dori EMAS) — string ro'yxati")),
                ('adherence_percent', models.PositiveSmallIntegerField(blank=True, help_text='Muolaja rejasining bajarilishi (%) — hisoblab yoziladi', null=True)),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('attention', "E'tibor talab"), ('critical', 'Jiddiy')], default='normal', max_length=10)),
                ('tokens_input', models.PositiveIntegerField(default=0)),
                ('tokens_output', models.PositiveIntegerField(default=0)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tracking_reports', to=settings.AUTH_USER_MODEL)),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_tracking_reports', to='users.patient')),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
                'indexes': [models.Index(fields=['patient', '-period_start'], name='tracking_ai_patient_5a262a_idx'), models.Index(fields=['severity', '-period_start'], name='tracking_ai_severit_2f429e_idx')],
                'constraints': [models.UniqueConstraint(fields=('patient_profile', 'period_start'), name='uniq_daily_tracking_report')],
            },
        ),
    ]
