# Generated by Django 5.2.13 on 2026-06-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuideVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=dict, help_text='3 tilli sarlavha {uz,ru,cyr}')),
                ('description', models.JSONField(blank=True, default=dict, help_text='3 tilli qisqa tavsif (ixtiyoriy)')),
                ('video_url', models.JSONField(default=dict, help_text='YouTube havola (3 tilli, odatda faqat uz)')),
                ('thumbnail_url', models.URLField(blank=True, help_text="Ixtiyoriy. Bo'sh bo'lsa mobil YouTube'dan avtomatik yasaydi.")),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text="Ixtiyoriy — '2:30' ko'rsatish uchun", null=True)),
                ('app_scope', models.CharField(choices=[('doctor', 'Doctor app'), ('patient', 'Patient app'), ('both', 'Ikkalasi')], default='both', help_text='Qaysi ilovaga tegishli (doctor/patient/both)', max_length=10)),
                ('category', models.CharField(choices=[('getting_started', 'Boshlash'), ('features', 'Imkoniyatlar'), ('billing', "To'lov"), ('other', 'Boshqa')], default='other', help_text="Ro'yxat ekrani bo'limi (kelajak)", max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib (kichik → tepada)')),
                ('is_active', models.BooleanField(default=True, help_text="False → mobil ro'yxatda qaytmaydi (yashiriladi)")),
                ('is_featured', models.BooleanField(default=False, help_text='Bosh sahifa banneri uchun')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['app_scope', 'is_active', 'order'], name='guides_guid_app_sco_0cf203_idx')],
            },
        ),
    ]
