# Generated by Django 6.0.3 on 2026-04-23 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetoken",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("fcm", "FCM (oddiy push)"),
                    ("voip_apns", "iOS VoIP PushKit"),
                ],
                default="fcm",
                help_text="FCM — oddiy push. voip_apns — iOS PushKit (incoming call).",
                max_length=12,
            ),
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(
                fields=["user", "token_type", "is_active"],
                name="notificatio_user_id_47db4c_idx",
            ),
        ),
    ]
