# Generated by Django 6.0.3 on 2026-04-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_devicetoken_token_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetoken",
            name="environment",
            field=models.CharField(
                choices=[
                    ("production", "Production (App Store / TestFlight)"),
                    ("development", "Development (Xcode debug build)"),
                ],
                default="production",
                help_text="APNS endpoint tanlash uchun (faqat voip_apns token uchun ahamiyatli). Xcode debug build'dan kelgan token — 'development', TestFlight va App Store build — 'production'.",
                max_length=12,
            ),
        ),
    ]
