# Generated by Django 5.2.13 on 2026-05-01 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_devicetoken_environment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('treatment_reminder', 'Muolaja eslatmasi'), ('appointment_created', "Yangi qabul so'rovi"), ('appointment_approved', 'Qabul tasdiqlandi'), ('appointment_rejected', 'Qabul rad etildi'), ('tariff_approved', 'Tarif tasdiqlandi'), ('tariff_rejected', 'Tarif rad etildi'), ('chat_message', 'Yangi xabar'), ('support_message', "Qo'llab-quvvatlash javobi"), ('call_missed', "Javobsiz qo'ng'iroq"), ('admin_broadcast', "Tizim e'loni"), ('system', 'Tizim xabari')], default='system', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
