# Generated by Django 5.2.13 on 2026-05-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('treatment_reminder', 'Muolaja eslatmasi'), ('appointment_created', "Yangi qabul so'rovi"), ('appointment_approved', 'Qabul tasdiqlandi'), ('appointment_rejected', 'Qabul rad etildi'), ('review_reminder', 'Review qoldirish eslatmasi'), ('tariff_approved', 'Tarif tasdiqlandi'), ('tariff_rejected', 'Tarif rad etildi'), ('chat_message', 'Yangi xabar'), ('support_message', "Qo'llab-quvvatlash javobi"), ('call_missed', "Javobsiz qo'ng'iroq"), ('admin_broadcast', "Tizim e'loni"), ('system', 'Tizim xabari')], default='system', max_length=32),
        ),
    ]
