# Generated by Django 5.2.13 on 2026-05-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='app_scope',
            field=models.CharField(blank=True, choices=[('patient', 'Patient app (com.mediik.patient)'), ('doctor', 'Doctor app (com.mediik.doctor)'), ('admin', 'Admin panel (web)')], help_text='Qaysi app tokenni registratsiya qilgan (patient/doctor/admin).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, help_text='iOS identifierForVendor yoki Android device ID', max_length=128),
        ),
    ]
