# Generated by Django 5.2.13 on 2026-05-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('treatment_reminder', 'Muolaja eslatmasi'), ('appointment_created', "Yangi qabul so'rovi"), ('appointment_approved', 'Qabul tasdiqlandi'), ('appointment_rejected', 'Qabul rad etildi'), ('review_reminder', 'Review qoldirish eslatmasi'), ('new_review', 'Yangi review keldi'), ('tariff_approved', 'Tarif tasdiqlandi'), ('tariff_rejected', 'Tarif rad etildi'), ('payout_completed', 'Pul yechish bajarildi'), ('payout_rejected', 'Pul yechish rad etildi'), ('chat_message', 'Yangi xabar'), ('support_message', "Qo'llab-quvvatlash javobi"), ('call_missed', "Javobsiz qo'ng'iroq"), ('connection_accepted', "Bog'lanish qabul qilindi"), ('connection_declined', "Bog'lanish rad etildi"), ('admin_broadcast', "Tizim e'loni"), ('system', 'Tizim xabari')], default='system', max_length=32),
        ),
    ]
