# Generated by Django 5.2.13 on 2026-07-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='app_scope',
            field=models.CharField(blank=True, db_index=True, help_text="'patient' | 'doctor' | 'admin' — qaysi ilovada ko'rinadi. null = barcha ilovalar (tizim/broadcast/legacy).", max_length=10, null=True),
        ),
    ]
