# Generated by Django 6.0.3 on 2026-03-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailySituationCheckup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("good", "Yaxshi"),
                            ("normal", "O'rtacha"),
                            ("bad", "Yomon"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
