# Generated by Django 6.0.3 on 2026-03-26 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_packages", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthIndicatorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name="dailysituationcheckup",
            options={"ordering": ["-date"]},
        ),
        migrations.CreateModel(
            name="HealthIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_indicators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "indicator_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="health_packages.healthindicatortype",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "indicator_type", "date")},
            },
        ),
    ]
