# Generated by Django 6.0.3 on 2026-03-26 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_packages", "0003_healthindicatortype_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dailysituationcheckup",
            index=models.Index(
                fields=["user", "date"], name="health_pack_user_id_671718_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthindicator",
            index=models.Index(
                fields=["user", "date"], name="health_pack_user_id_6b00c6_idx"
            ),
        ),
    ]
