# Generated by Django 6.0.3 on 2026-04-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "health_packages",
            "0004_dailysituationcheckup_health_pack_user_id_671718_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="healthindicator",
            name="value_secondary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ikkinchi qiymat (faqat range tipi uchun, masalan diastolic)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="healthindicatortype",
            name="value_format",
            field=models.CharField(
                choices=[
                    ("number", "Bitta son"),
                    ("range", "Ikki son (masalan qon bosimi 120/80)"),
                ],
                default="number",
                help_text="number = bitta qiymat (vazn, harorat). range = ikki qiymat (qon bosimi).",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="healthindicator",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Asosiy qiymat (range bo'lsa systolic)",
                max_digits=10,
            ),
        ),
    ]
