# Generated by Django 6.0.3 on 2026-04-09 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_packages", "0005_healthindicator_value_secondary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailysituationcheckup",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
