# Generated by Django 6.0.3 on 2026-04-20 17:48

from django.db import migrations


MACROS_TYPES = [
    {"name": "Kaloriya", "unit": "kcal", "icon": "🔥"},
    {"name": "Uglevod", "unit": "g", "icon": "🌾"},
    {"name": "Oqsil", "unit": "g", "icon": "🥩"},
    {"name": "Yog'", "unit": "g", "icon": "🥑"},
]


def add_macros_types(apps, schema_editor):
    HealthIndicatorType = apps.get_model("health_packages", "HealthIndicatorType")
    for item in MACROS_TYPES:
        HealthIndicatorType.objects.get_or_create(
            name=item["name"],
            defaults={"unit": item["unit"], "icon": item["icon"]},
        )


def remove_macros_types(apps, schema_editor):
    HealthIndicatorType = apps.get_model("health_packages", "HealthIndicatorType")
    HealthIndicatorType.objects.filter(
        name__in=[m["name"] for m in MACROS_TYPES]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("health_packages", "0006_alter_dailysituationcheckup_date"),
    ]

    operations = [
        migrations.RunPython(add_macros_types, remove_macros_types),
    ]
