# Generated by Django 5.2.13 on 2026-05-04 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_packages', '0007_add_macros_indicator_types'),
        ('users', '0008_backfill_patient_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysituationcheckup',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='situation_checkups', to='users.patient'),
        ),
        migrations.AddField(
            model_name='healthindicator',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_indicators', to='users.patient'),
        ),
    ]
