# Generated by Django 5.2.13 on 2026-05-25 06:09

from datetime import datetime, time

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_recorded_at_and_source(apps, schema_editor):
    """Eski qatorlarga recorded_at = sana + 12:00 (Tashkent), source = mavjud
    indicator_type.system_key'ga qarab `diet_ai` yoki `manual`.

    Optimallashtirish: SQLite lock pressure'ni kamaytirish uchun `bulk_update`
    chunk'larda, har chunk alohida tranzaksiya (migration `atomic=False`).
    """
    HealthIndicator = apps.get_model("health_packages", "HealthIndicator")
    HealthIndicatorType = apps.get_model("health_packages", "HealthIndicatorType")
    diet_keys = {"calories", "carbs", "protein", "fat"}
    diet_type_ids = set(
        HealthIndicatorType.objects.filter(system_key__in=diet_keys).values_list("id", flat=True)
    )
    tz = timezone.get_current_timezone()

    qs = HealthIndicator.objects.only("id", "date", "indicator_type_id").order_by("id")
    batch = []
    BATCH_SIZE = 500
    for ind in qs.iterator(chunk_size=BATCH_SIZE):
        if ind.date is None:
            continue
        naive = datetime.combine(ind.date, time(12, 0))
        ind.recorded_at = timezone.make_aware(naive, tz)
        ind.source = "diet_ai" if ind.indicator_type_id in diet_type_ids else "manual"
        batch.append(ind)
        if len(batch) >= BATCH_SIZE:
            HealthIndicator.objects.bulk_update(batch, ["recorded_at", "source"])
            batch.clear()
    if batch:
        HealthIndicator.objects.bulk_update(batch, ["recorded_at", "source"])


def reverse_noop(apps, schema_editor):
    """Reverse — heq narsani qaytarmaymiz (rollback paytida unique_together
    qaytadan o'rnatiladi, lekin data hech qachon yo'qolmaydi)."""
    pass


class Migration(migrations.Migration):
    # SQLite + ko'p connection: data backfill katta tranzaksiyada qolib boshqa
    # processlarning lock'iga to'qnashmasligi uchun har step alohida.
    atomic = False

    dependencies = [
        ('health_packages', '0011_indicatortype_system_key'),
        ('users', '0008_backfill_patient_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthindicator',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AlterUniqueTogether(
            name='healthindicator',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='healthindicator',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text="Uyqu uchun stages, va boshqa ixtiyoriy ma'lumotlar"),
        ),
        migrations.AddField(
            model_name='healthindicator',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="O'lchov vaqti (braslent vaqti yoki kiritilgan vaqti)"),
        ),
        migrations.AddField(
            model_name='healthindicator',
            name='source',
            field=models.CharField(choices=[('manual', "Qo'lda"), ('bracelet', 'Braslent'), ('diet_ai', 'Ovqat (Diet AI)')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='healthindicator',
            name='date',
            field=models.DateField(db_index=True, help_text="recorded_at'dan avto-hisoblanadi (kunlik query'lar uchun)"),
        ),
        # Data backfill — eski qatorlar uchun recorded_at va source o'rnatish
        migrations.RunPython(backfill_recorded_at_and_source, reverse_code=reverse_noop),
        migrations.AddIndex(
            model_name='healthindicator',
            index=models.Index(fields=['user', 'indicator_type', 'recorded_at'], name='health_pack_user_id_67ed0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthindicator',
            constraint=models.UniqueConstraint(fields=('user', 'indicator_type', 'recorded_at', 'source'), name='health_indicator_unique_event'),
        ),
    ]
