# Generated by Django 5.2.13 on 2026-06-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_packages', '0013_seed_bracelet_metric_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthindicatortype',
            name='category',
            field=models.CharField(choices=[('manual', "Qo'lda kiritiladigan"), ('wearable', "Braslet o'lchaydigan"), ('diet', 'Ovqat (Diet AI)')], default='manual', help_text="UI shu flag bo'yicha turni joylashtiradi: manual=qo'lda dialog, wearable=jonli braslet karta, diet=Diet AI. Taxmin emas — aniq belgilanadi.", max_length=10),
        ),
        migrations.AddField(
            model_name='healthindicatortype',
            name='manual_entry',
            field=models.BooleanField(default=True, help_text="False bo'lsa qo'lda qo'shish dialogida ko'rinmaydi. Kumulyativ braslet turlari (Qadam, Uyqu, Masofa, MET, Yondirilgan kaloriya) uchun false — braslet + qo'lda yig'indisi ikki marta sanalmasin."),
        ),
    ]
