# Generated by Django 5.2.13 on 2026-07-27 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_packages', '0015_backfill_indicator_category'),
        ('users', '0009_alter_user_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='healthindicator',
            index=models.Index(fields=['user', 'indicator_type', 'date'], name='health_pack_user_id_9b0692_idx'),
        ),
    ]
