# Generated by Django 5.2.13 on 2026-08-15 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_packages', '0016_healthindicator_health_pack_user_id_9b0692_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthindicator',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="O'lchov vaqti (kiritilgan vaqt)"),
        ),
        migrations.AlterField(
            model_name='healthindicator',
            name='source',
            field=models.CharField(choices=[('manual', "Qo'lda"), ('diet_ai', 'Ovqat (Diet AI)')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='healthindicatortype',
            name='category',
            field=models.CharField(choices=[('manual', "Qo'lda kiritiladigan"), ('diet', 'Ovqat (Diet AI)')], default='manual', help_text="UI shu flag bo'yicha turni joylashtiradi: manual=qo'lda dialog, diet=Diet AI. Taxmin emas — aniq belgilanadi.", max_length=10),
        ),
        migrations.AlterField(
            model_name='healthindicatortype',
            name='manual_entry',
            field=models.BooleanField(default=True, help_text="False bo'lsa qo'lda qo'shish dialogida ko'rinmaydi (masalan, faqat tizim yozadigan turlar uchun)."),
        ),
    ]
