# Generated by Django 6.0.3 on 2026-04-07 08:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctors", "0003_doctorpatient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProFeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("icon", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "key"],
            },
        ),
        migrations.CreateModel(
            name="ProPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("duration_days", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="UI da ko'rsatish uchun"
                    ),
                ),
                ("is_popular", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "duration_days"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="DoctorBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_earned",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_withdrawn",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to="doctors.doctorprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorTariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "duration_days",
                    models.PositiveIntegerField(help_text="Doctor belgilaydi"),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list, help_text="Erkin matnli imkoniyatlar"
                    ),
                ),
                ("discount_enabled", models.BooleanField(default=False)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Foiz"), ("amount", "So'mda")],
                        default="percent",
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "discount_target",
                    models.CharField(
                        choices=[("all", "Hamma"), ("new_patients", "Yangi bemorlar")],
                        default="all",
                        max_length=15,
                    ),
                ),
                ("discount_expires_at", models.DateField(blank=True, null=True)),
                ("discount_label", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("approved", "Tasdiqlangan"),
                            ("rejected", "Rad etilgan"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to="doctors.doctorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("payme", "Payme"),
                            ("click", "Click"),
                            ("uzum", "Uzum"),
                            ("paynet", "Paynet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("completed", "Yakunlangan"),
                            ("failed", "Xatolik"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("pro_subscription", "Pro obuna"),
                            ("doctor_tariff", "Doctor tarifi"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DoctorTariffPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tariff_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Tarif ma'lumotlari sotib olingan paytdagi nusxasi",
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "doctor_earnings",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariff_sales",
                        to="doctors.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariff_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to="payments.doctortariff",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tariff_purchase",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Plan nomi/narxi/muddati sotib olingan paytdagi nusxasi",
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pro_subscription",
                        to="payments.payment",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="payments.proplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pro_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="doctortariff",
            index=models.Index(
                fields=["doctor", "status"], name="payments_do_doctor__202b3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctortariff",
            index=models.Index(
                fields=["status", "is_active"], name="payments_do_status_171851_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "status"], name="payments_pa_user_id_01767a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["provider", "status"], name="payments_pa_provide_cc7861_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["purpose", "status"], name="payments_pa_purpose_8579eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctortariffpurchase",
            index=models.Index(
                fields=["patient", "expires_at"], name="payments_do_patient_48a7fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctortariffpurchase",
            index=models.Index(
                fields=["doctor", "created_at"], name="payments_do_doctor__2da29a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prosubscription",
            index=models.Index(
                fields=["user", "expires_at"], name="payments_pr_user_id_b777ab_idx"
            ),
        ),
    ]
