# Generated by Django 6.0.3 on 2026-04-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctortariff",
            name="is_popular",
            field=models.BooleanField(default=False, help_text="'Mashhur' badge"),
        ),
    ]
