# Generated by Django 5.2.13 on 2026-04-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_diet_ai_feature_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum')], max_length=20),
        ),
    ]
