# Generated by Django 5.2.13 on 2026-05-04 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_provider'),
        ('users', '0008_backfill_patient_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortariffpurchase',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_purchases', to='users.patient'),
        ),
        migrations.AddField(
            model_name='prosubscription',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_subscriptions', to='users.patient'),
        ),
    ]
