# Generated by Django 5.2.13 on 2026-05-05 13:37

from django.db import migrations, models


def backfill_balance_id(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    Payment.objects.filter(balance_id__isnull=True).update(
        balance_id=models.F("id")
    )


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_backfill_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.RunPython(backfill_balance_id, reverse_noop),
    ]
