# Generated by Django 5.2.13 on 2026-05-07 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_backfill_doctorpatient_patient_profile'),
        ('payments', '0007_add_balance_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=19)),
                ('card_holder', models.CharField(max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_method', to='doctors.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('card_number', models.CharField(max_length=19)),
                ('card_holder', models.CharField(max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarilgan'), ('rejected', 'Rad etilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=15)),
                ('admin_note', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('transaction_ref', models.CharField(blank=True, help_text='Bank tranzaksiya ID si (ixtiyoriy)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='doctors.doctorprofile')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', 'status'], name='payments_pa_doctor__ad6c35_idx'), models.Index(fields=['status', '-created_at'], name='payments_pa_status_6374b8_idx')],
            },
        ),
    ]
