# Generated by Django 5.2.13 on 2026-05-14 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_doctorpayoutcard_payout_substatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum'), ('atmos', 'Atmos')], max_length=20),
        ),
        migrations.CreateModel(
            name='AtmosSavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atmos_card_id', models.BigIntegerField(help_text='Atmos tomondagi card_id', unique=True)),
                ('card_token', models.TextField(help_text="Atmos card_token — to'lovda ishlatiladi")),
                ('pan_masked', models.CharField(help_text='986009******1840', max_length=20)),
                ('expiry', models.CharField(help_text='YYMM, masalan 2505', max_length=4)),
                ('card_holder', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atmos_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['user', '-is_primary'], name='payments_at_user_id_4b662c_idx')],
            },
        ),
    ]
