# Generated by Django 5.2.13 on 2026-05-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_i18n_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpayoutcard',
            name='atmos_asl_card_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ATMOS ASL tomondagi karta ID — /info chaqirilganda olinadi', null=True),
        ),
        migrations.AddField(
            model_name='doctorpayoutcard',
            name='atmos_asl_phone',
            field=models.CharField(blank=True, help_text="ASL qaytargan karta-ga bog'langan telefon raqami", max_length=20),
        ),
        migrations.AddField(
            model_name='doctorpayoutcard',
            name='atmos_asl_processing_type',
            field=models.CharField(blank=True, help_text='UZCARD / HUMO — ASL processing_type', max_length=20),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='atmos_asl_error',
            field=models.CharField(blank=True, help_text="state=5 bo'lganda billing_error_message; yoki API error description", max_length=500),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='atmos_asl_ext_id',
            field=models.CharField(blank=True, db_index=True, help_text="ASL ga jo'natilgan idempotency key (uuid4)", max_length=64),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='atmos_asl_poll_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Necha marta /id orqali pollangan (debug uchun)'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='atmos_asl_state',
            field=models.SmallIntegerField(blank=True, help_text='Oxirgi ASL state: 2=ACCEPTED, 4=FINISHED, 5=FAILED, 13=PENDING', null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='atmos_asl_transaction_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ASL tomondagi transaction_id (/create javobidan)', null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='method',
            field=models.CharField(choices=[('manual', "Qo'lda (admin bank o'tkazma qiladi)"), ('atmos_asl', 'ATMOS ASL (avtomatik)')], default='manual', help_text="MANUAL — admin bank o'tkazma · ATMOS_ASL — avtomatik API", max_length=15),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='sub_status',
            field=models.CharField(choices=[('submitted', 'Yuborildi'), ('in_review', 'Tekshirilmoqda'), ('atmos_processing', 'ATMOS orqali ishlanmoqda')], default='submitted', help_text='Pending paytida UI uchun batafsil holat', max_length=20),
        ),
    ]
