# Generated by Django 5.2.13 on 2026-06-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_doctortariffpurchase_available_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmossavedcard',
            name='card_number',
            field=models.CharField(blank=True, help_text="To'liq PAN — pre-apply uchun", max_length=16),
        ),
        migrations.AlterField(
            model_name='atmossavedcard',
            name='card_token',
            field=models.TextField(help_text='Atmos card_token — remove_card uchun'),
        ),
    ]
