# Generated by Django 5.2.13 on 2026-06-24 10:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_cleanup_orphan_doctorpatient'),
        ('payments', '0014_atmossavedcard_card_number_and_more'),
        ('users', '0009_alter_user_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorbalance',
            name='total_commission_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Offline to'lovlar uchun balansdan yechilgan platforma komissiyasi (jami).", max_digits=14),
        ),
        migrations.AddField(
            model_name='doctorbalance',
            name='total_topped_up',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Doctor o'zi to'ldirgan summa (jami) — earnings emas.", max_digits=14),
        ),
        migrations.AddField(
            model_name='doctortariffpurchase',
            name='source',
            field=models.CharField(choices=[('online', "Online to'lov"), ('offline', 'Offline (naqd) — doctor tasdiqlagan')], default='online', help_text="Online to'lov yoki offline (naqd, doctor tasdiqlagan).", max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('pro_subscription', 'Pro obuna'), ('doctor_tariff', 'Doctor tarifi'), ('balance_topup', "Balans to'ldirish")], max_length=30),
        ),
        migrations.CreateModel(
            name='BalanceTopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_topups', to='doctors.doctorprofile')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_topup', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', '-created_at'], name='payments_ba_doctor__4be2aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfflinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_snapshot', models.JSONField(default=dict, help_text="Tarif ma'lumotlari so'rov paytidagi nusxasi")),
                ('amount', models.DecimalField(decimal_places=2, help_text="So'rov paytida kelishilgan narx (snapshot).", max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Tasdiqlash kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10)),
                ('commission_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Tasdiqlangan/rad etilgan vaqt.', null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_offline_payments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_payments', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_payments', to=settings.AUTH_USER_MODEL)),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_payments', to='users.patient')),
                ('purchase', models.OneToOneField(blank=True, help_text='Tasdiqlanganda yaratilgan tarif xaridi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_payment', to='payments.doctortariffpurchase')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_payments', to='payments.doctortariff')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', 'status'], name='payments_of_doctor__4aea0a_idx'), models.Index(fields=['patient', 'status'], name='payments_of_patient_cb5544_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('patient', 'doctor'), name='unique_pending_offline_payment')],
            },
        ),
    ]
