# Generated by Django 5.2.13 on 2026-08-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_alter_payment_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('pro_subscription', 'Pro obuna'), ('doctor_tariff', 'Doctor tarifi'), ('balance_topup', "Balans to'ldirish"), ('consultation', 'Konsultatsiya')], max_length=30),
        ),
    ]
