# Generated by Django 5.2.13 on 2026-08-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_alter_payment_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('atmos', 'Atmos'), ('manual', "Qo'lda (test)"), ('cash', 'Naqd (kassa)')], max_length=20),
        ),
    ]
