# Generated by Django 5.2.13 on 2026-08-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_alter_payment_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('pro_subscription', 'Pro obuna'), ('doctor_tariff', 'Doctor tarifi'), ('balance_topup', "Balans to'ldirish"), ('consultation', 'Konsultatsiya'), ('online_reception', 'Onlayn qabulxona')], max_length=30),
        ),
    ]
