# Generated by Django 5.2.13 on 2026-05-04 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
        ('users', '0008_backfill_patient_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcard',
            name='patient_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_card', to='users.patient'),
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_conditions', to='users.patient'),
        ),
        migrations.AddField(
            model_name='medicalnote',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_notes', to='users.patient'),
        ),
    ]
