# Generated by Django 5.2.13 on 2026-05-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_backfill_doctorpatient_patient_profile'),
        ('medical', '0003_backfill_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcard',
            name='doctor_profile',
            field=models.ForeignKey(blank=True, help_text="Kartani yangilangan doctor (admin yangilagan bo'lsa null).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_cards', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='doctor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_conditions', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='medicalnote',
            name='doctor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_notes', to='doctors.doctorprofile'),
        ),
    ]
