# Generated by Django 5.2.13 on 2026-05-15 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_alter_specialty_options_alter_specialty_name'),
        ('medical', '0005_backfill_doctor_profile'),
        ('users', '0008_backfill_patient_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=60)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('normal_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('normal_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('prescribed', 'Tayinlangan'), ('submitted', 'Topshirilgan'), ('reviewed', "Ko'rib chiqilgan"), ('cancelled', 'Bekor qilingan')], default='prescribed', max_length=20)),
                ('note', models.TextField(blank=True, help_text="Doctor qo'shimcha izohi")),
                ('verdict', models.CharField(blank=True, help_text="Doctor xulosasi (masalan, 'Norma chegarasida').", max_length=160)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text='Deadline reminder yuborilgan vaqt (idempotency)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_analyses', to=settings.AUTH_USER_MODEL)),
                ('doctor_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_analyses', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='users.patient')),
                ('indicators', models.ManyToManyField(blank=True, related_name='prescriptions', to='medical.analysisindicator')),
                ('preparations', models.ManyToManyField(blank=True, related_name='prescriptions', to='medical.analysispreparation')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medical.analysistype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(blank=True, help_text='DO Spaces S3 key. Frontend Bunny CDN token URL orqali ochadi.', max_length=500)),
                ('file_mime', models.CharField(blank=True, max_length=80)),
                ('patient_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='medical.analysis')),
            ],
        ),
        migrations.AddField(
            model_name='analysispreparation',
            name='type',
            field=models.ForeignKey(blank=True, help_text="None bo'lsa universal.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='medical.analysistype'),
        ),
        migrations.AddField(
            model_name='analysisindicator',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='medical.analysistype'),
        ),
        migrations.CreateModel(
            name='AnalysisResultValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_values', to='medical.analysisindicator')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='medical.analysisresult')),
            ],
            options={
                'indexes': [models.Index(fields=['indicator', '-id'], name='medical_ana_indicat_0b68b8_idx')],
                'unique_together': {('result', 'indicator')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='analysisindicator',
            unique_together={('type', 'code')},
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['patient', 'status'], name='medical_ana_patient_fee0ff_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['doctor', 'status'], name='medical_ana_doctor__a44ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['status', 'deadline_at'], name='medical_ana_status_323ed2_idx'),
        ),
    ]
