# Generated by Django 5.2.13 on 2026-05-16 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_alter_specialty_options_alter_specialty_name'),
        ('medical', '0006_analysisindicator_analysispreparation_analysistype_and_more'),
        ('users', '0008_backfill_patient_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(help_text='DO Spaces S3 key. Frontend Bunny CDN signed URL orqali ochadi.', max_length=500)),
                ('file_mime', models.CharField(blank=True, max_length=80)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='is_private',
            field=models.BooleanField(default=False, help_text="True bo'lsa 'Faqat o'zim ko'raman' — hech qaysi doctorga yuborilmaydi."),
        ),
        migrations.AddField(
            model_name='analysis',
            name='patient_viewed_at',
            field=models.DateTimeField(blank=True, help_text="Bemor doctor sharhini ko'rgan vaqt (KO'RILDI status uchun).", null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text="patient_uploaded uchun: bemor kimga yuborgani (ko'p doctor).", related_name='received_analyses', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recorded_at',
            field=models.DateField(blank=True, help_text='patient_uploaded: analiz topshirilgan sana (laboratoriyada).', null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='source',
            field=models.CharField(choices=[('doctor_prescribed', 'Doctor tayinlagan'), ('patient_uploaded', 'Bemor yuklagan')], default='doctor_prescribed', max_length=20),
        ),
        migrations.AddField(
            model_name='analysis',
            name='title',
            field=models.CharField(blank=True, help_text="Bemor qo'ygan nom ('Umumiy qon tahlili'). Bo'sh bo'lsa type.name.", max_length=255),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='doctor_prescribed: tayinlagan doctor. patient_uploaded: birinchi sharh yozgan doctor (avto-tayinlanadi).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('prescribed', 'Tayinlangan'), ('submitted', 'Yuborilgan'), ('reviewed', 'Sharhlangan'), ('cancelled', 'Bekor qilingan'), ('private', "Faqat o'zim")], default='prescribed', max_length=20),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='verdict',
            field=models.TextField(blank=True, help_text='Doctor xulosasi/sharhi (uzun matn).'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='file_key',
            field=models.CharField(blank=True, help_text='DEPRECATED — yangi multi-file uchun AnalysisFile ishlatiladi.', max_length=500),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['patient', 'source', '-created_at'], name='medical_ana_patient_2efc6e_idx'),
        ),
        migrations.AddField(
            model_name='analysisfile',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='medical.analysis'),
        ),
        migrations.AddField(
            model_name='analysisfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analysisfile',
            index=models.Index(fields=['analysis', 'order'], name='medical_ana_analysi_585936_idx'),
        ),
    ]
