# Generated by Django 5.2.13 on 2026-05-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_cleanup_orphan_doctorpatient'),
        ('medical', '0007_analysisfile_analysis_is_private_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='is_private',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text="patient_uploaded uchun: bemorning bog'langan doctorlari (avto-set, push notification targeting uchun).", related_name='received_analyses', to='doctors.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('prescribed', 'Tayinlangan'), ('submitted', 'Yuborilgan'), ('reviewed', 'Sharhlangan'), ('cancelled', 'Bekor qilingan')], default='prescribed', max_length=20),
        ),
    ]
