# Generated by Django 5.2.13 on 2026-05-16 13:26

from django.db import migrations, models


def _guess_category(code: str) -> str:
    """Code'dan category aniqlash. Underscore va dash separatorlarni qo'llaydi."""
    norm = (code or "").replace("-", "_").lower()
    if "blood" in norm or "qon" in norm:
        return "blood"
    if "urine" in norm or "siydik" in norm:
        return "urine"
    if any(
        kw in norm
        for kw in ("xray", "rentgen", "uzi", "ultrasound", "mri", "ct", "ultratovush")
    ):
        return "imaging"
    if any(kw in norm for kw in ("ecg", "ekg", "exocg", "exokg", "exo_kg", "yurak")):
        return "cardiac"
    if "hormon" in norm or "gormon" in norm:
        return "hormones"
    if any(kw in norm for kw in ("pcr", "antitelo", "covid", "infek")):
        return "infection"
    return "other"


def backfill_category(apps, schema_editor):
    AnalysisType = apps.get_model("medical", "AnalysisType")
    for at in AnalysisType.objects.all():
        at.category = _guess_category(at.code)
        at.save(update_fields=["category"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_analysis_catalog_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistype',
            name='category',
            field=models.CharField(choices=[('blood', 'Qon'), ('urine', 'Siydik'), ('imaging', 'Tasvir (UZI, Rentgen)'), ('cardiac', 'Yurak (EKG, EXOKG)'), ('hormones', 'Gormonlar'), ('infection', 'Infeksiya'), ('other', 'Boshqa')], db_index=True, default='other', help_text='Frontend tabi uchun (Qon / Siydik / Tasvir / ...).', max_length=20),
        ),
        migrations.RunPython(backfill_category, noop_reverse),
    ]
