# Generated by Django 5.2.13 on 2026-05-18 07:06

from django.db import migrations, models


def _drop_patient_viewed_at_if_exists(apps, schema_editor):
    """Dev SQLite DB'da column allaqachon yo'q bo'lishi mumkin — defensive drop.

    Default RemoveField ALTER TABLE DROP COLUMN qiladi, agar column yo'q
    bo'lsa fail bo'ladi. Bu yerda introspection bilan oldindan tekshiramiz.
    """
    connection = schema_editor.connection
    table_name = "medical_analysis"
    with connection.cursor() as cursor:
        columns = {
            col.name
            for col in connection.introspection.get_table_description(
                cursor, table_name
            )
        }
        if "patient_viewed_at" not in columns:
            return
        quoted_table = connection.ops.quote_name(table_name)
        quoted_column = connection.ops.quote_name("patient_viewed_at")
        cursor.execute(f"ALTER TABLE {quoted_table} DROP COLUMN {quoted_column}")


def _readd_patient_viewed_at(apps, schema_editor):
    """Reverse — patient_viewed_at column'ni qaytarish (rollback uchun)."""
    connection = schema_editor.connection
    table_name = "medical_analysis"
    with connection.cursor() as cursor:
        columns = {
            col.name
            for col in connection.introspection.get_table_description(
                cursor, table_name
            )
        }
        if "patient_viewed_at" in columns:
            return
        quoted_table = connection.ops.quote_name(table_name)
        quoted_column = connection.ops.quote_name("patient_viewed_at")
        cursor.execute(
            f"ALTER TABLE {quoted_table} ADD COLUMN {quoted_column} "
            f"datetime NULL"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_add_analysistype_category'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='analysis',
                    name='patient_viewed_at',
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    _drop_patient_viewed_at_if_exists,
                    _readd_patient_viewed_at,
                ),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='doctor_viewed_at',
            field=models.DateTimeField(blank=True, help_text="Doctor bemor analizini ko'rgan vaqt (KO'RILDI status uchun).", null=True),
        ),
    ]
