# Generated by Django 5.2.13 on 2026-05-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_replace_patient_viewed_with_doctor_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='custom_indicators',
            field=models.JSONField(blank=True, default=list, help_text="Doctor 'Boshqa' tugmasi orqali qo'shgan qo'shimcha ko'rsatkichlar (erkin matn)."),
        ),
        migrations.AddField(
            model_name='analysis',
            name='custom_preparations',
            field=models.JSONField(blank=True, default=list, help_text="Doctor 'Boshqa' tugmasi orqali qo'shgan qo'shimcha tayyorgarliklar (erkin matn)."),
        ),
    ]
