# Generated by Django 5.2.13 on 2026-05-20 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_analysis_custom_indicators_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalNoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(help_text='DO Spaces S3 key. Frontend Bunny CDN signed URL orqali ochadi.', max_length=500)),
                ('file_mime', models.CharField(blank=True, max_length=80)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='medical.medicalnote')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
                'indexes': [models.Index(fields=['note', 'order'], name='medical_med_note_id_4b1e93_idx')],
            },
        ),
    ]
