# Generated by Django 5.2.13 on 2026-05-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_medicalnoteimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalnote',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
