# Generated by Django 5.2.13 on 2026-07-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0014_alter_medicalnote_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcard',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
