# Generated by Django 5.2.13 on 2026-08-15 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0015_medicalcard_height_cm_medicalcard_weight_kg'),
        ('treatment', '0014_prescriptionscan'),
        ('users', '0009_alter_user_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcondition',
            name='icd10',
            field=models.CharField(blank=True, help_text='ICD-10 kodi (masalan I10)', max_length=10),
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='is_active',
            field=models.BooleanField(default=False, help_text="Navigator hozir shu tashxis bo'yicha yo'l xaritasi yuritayaptimi"),
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='plain_explanation',
            field=models.TextField(blank=True, help_text="Kasallikning oddiy tildagi tushuntirishi (bemorga ko'rsatiladi)"),
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('first_week', 'Birinchi hafta'), ('first_month', 'Birinchi oy'), ('ongoing', 'Doimiy')], max_length=15)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('specialist', models.CharField(blank=True, help_text="Mutaxassis chipi (Kardiolog, Laboratoriya...). Bo'sh = o'z-o'ziga qadam", max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Bajarilmagan'), ('completed', 'Bajarilgan')], default='pending', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_steps', to='medical.medicalcondition')),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_steps', to='users.patient')),
                ('treatment', models.ForeignKey(blank=True, help_text="Dori qadami muolajaga bog'langan bo'lsa", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_steps', to='treatment.treatment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['period', 'order', 'id'],
                'indexes': [models.Index(fields=['user', 'status'], name='medical_roa_user_id_efb1ec_idx'), models.Index(fields=['condition', 'period'], name='medical_roa_conditi_7759af_idx')],
            },
        ),
    ]
