# Generated by Django 5.2.13 on 2026-08-15 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0015_medicalcard_height_cm_medicalcard_weight_kg'),
        ('treatment', '0014_prescriptionscan'),
        ('users', '0009_alter_user_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcondition',
            name='extraction',
            field=models.JSONField(blank=True, help_text="from-image: AI o'qish natijasi {confidence, recognized_text, needs_review}. Rasm o'zi SAQLANMAYDI (maxfiylik).", null=True),
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='icd10',
            field=models.CharField(blank=True, help_text='ICD-10 kodi (masalan I10)', max_length=10),
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='is_active',
            field=models.BooleanField(default=False, help_text="Navigator hozir shu tashxis bo'yicha yo'l xaritasi yuritayaptimi"),
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='plain_explanation',
            field=models.TextField(blank=True, help_text="Kasallikning oddiy tildagi tushuntirishi (bemorga ko'rsatiladi)"),
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='red_flags',
            field=models.JSONField(blank=True, default=list, help_text='Xavfli belgilar [{text, action, severity}]'),
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='source',
            field=models.CharField(choices=[('doctor', 'Platformadagi shifokor'), ('document', "Tashxis qog'ozi (AI o'qidi)"), ('manual', "Bemor o'zi kiritdi"), ('integration', 'Tashqi tizim')], default='manual', help_text='Tashxis qayerdan keldi (navigator kontrakti: DiagnosisSource)', max_length=15),
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='what_to_watch',
            field=models.JSONField(blank=True, default=list, help_text="Nimalarni kuzatish kerak — string ro'yxati"),
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(choices=[('medication', 'Dori qabul qilish'), ('analysis', 'Analiz topshirish'), ('consultation', 'Shifokorga murojaat'), ('lifestyle', 'Turmush tarzi / parhez'), ('checkup', "Nazorat ko'rigi"), ('education', "Tushuntirish / o'qish")], max_length=15)),
                ('status', models.CharField(choices=[('done', 'Bajarilgan'), ('current', 'Hozir bajarilishi kerak'), ('locked', 'Yopiq'), ('skipped', "O'tkazib yuborilgan")], default='locked', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('body', models.TextField(blank=True, help_text="education qadam uchun to'liq matn (sheet'da ochiladi)")),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, help_text="Tur-ga bog'liq ma'lumot (kontrakt §2 payload qoidalari)", null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_steps', to='medical.medicalcondition')),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_steps', to='users.patient')),
                ('treatment', models.ForeignKey(blank=True, help_text="medication qadamidan yaratilgan muolaja (bo'lsa)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_steps', to='treatment.treatment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['user', 'status'], name='medical_roa_user_id_efb1ec_idx'), models.Index(fields=['condition', 'order'], name='medical_roa_conditi_d452de_idx')],
            },
        ),
    ]
