# Generated by Django 6.0.3 on 2026-03-26 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "specialties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("license_number", models.CharField(blank=True, max_length=50)),
                ("workplace", models.CharField(blank=True, max_length=255)),
                (
                    "consultation_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("total_patients", models.PositiveIntegerField(default=0)),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("is_online", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("accepts_online", models.BooleanField(default=True)),
                ("accepts_offline", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctors",
                        to="doctors.specialty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("issuer", models.CharField(blank=True, max_length=255)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctors/certificates/"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="doctors.doctorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Dushanba"),
                            (1, "Seshanba"),
                            (2, "Chorshanba"),
                            (3, "Payshanba"),
                            (4, "Juma"),
                            (5, "Shanba"),
                            (6, "Yakshanba"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_duration", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="doctors.doctorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "weekday", "is_active"],
                        name="doctors_doc_doctor__e6f19d_idx",
                    )
                ],
                "unique_together": {("doctor", "weekday")},
            },
        ),
        migrations.AddIndex(
            model_name="doctorprofile",
            index=models.Index(
                fields=["specialty", "is_verified"],
                name="doctors_doc_special_c1e7b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="doctorprofile",
            index=models.Index(fields=["rating"], name="doctors_doc_rating_63ebc1_idx"),
        ),
    ]
