# Generated by Django 6.0.3 on 2026-03-26 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("reason", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.RemoveIndex(
            model_name="doctorprofile",
            name="doctors_doc_rating_63ebc1_idx",
        ),
        migrations.AddField(
            model_name="blockedslot",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_slots",
                to="doctors.doctorprofile",
            ),
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="consultation_price",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="is_online",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="total_patients",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="total_reviews",
        ),
        migrations.AddIndex(
            model_name="blockedslot",
            index=models.Index(
                fields=["doctor", "date"], name="doctors_blo_doctor__bc0d0e_idx"
            ),
        ),
    ]
