# Generated by Django 6.0.3 on 2026-04-20 17:46

from django.conf import settings
from django.db import migrations, models


def backfill_requested_by(apps, schema_editor):
    """Eski DoctorPatient yozuvlari uchun requested_by = added_by (source of truth)."""
    DoctorPatient = apps.get_model("doctors", "DoctorPatient")
    for dp in DoctorPatient.objects.all():
        if dp.added_by in ("doctor", "patient"):
            dp.requested_by = dp.added_by
            dp.save(update_fields=["requested_by"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0004_certificate_image_to_s3_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorpatient",
            name="requested_by",
            field=models.CharField(
                choices=[("doctor", "Doctor"), ("patient", "Patient")],
                default="patient",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="doctorpatient",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorpatient",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Kutilmoqda"),
                    ("accepted", "Qabul qilingan"),
                    ("declined", "Rad etilgan"),
                ],
                default="accepted",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="doctorpatient",
            index=models.Index(
                fields=["status", "requested_by"], name="doctors_doc_status_8975e1_idx"
            ),
        ),
        migrations.RunPython(backfill_requested_by, noop_reverse),
    ]
