# Generated by Django 5.2.13 on 2026-05-04 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_remove_legacy_schedule'),
        ('users', '0008_backfill_patient_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatient',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_relationships', to='users.patient'),
        ),
    ]
