# Generated by Django 5.2.13 on 2026-07-01 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_cleanup_orphan_doctorpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='specialties',
            field=models.ManyToManyField(blank=True, help_text='Doctor mutaxassisliklari (bir nechta). `specialty` — birinchisi (asosiy).', related_name='doctors_multi', to='doctors.specialty'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.ForeignKey(blank=True, help_text="Asosiy mutaxassislik (`specialties` ro'yxatining birinchisi — orqaga moslik).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='doctors.specialty'),
        ),
    ]
