# Generated by Django 5.2.13 on 2026-07-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_backfill_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
