# Generated by Django 5.2.13 on 2026-07-28 06:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_doctorprofile_deleted_at_doctorprofile_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Shu doctor uchun individual komissiya (%). Bo'sh bo'lsa global SystemSetting[doctor_commission_percent] olinadi.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
