# Generated by Django 5.2.13 on 2026-08-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0016_doctorprofile_commission_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='marketplace_visible',
            field=models.BooleanField(default=True),
        ),
    ]
