# Generated by Django 5.2.13 on 2026-08-05 12:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0017_doctorprofile_marketplace_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_duration_min',
            field=models.PositiveIntegerField(default=30, help_text='Konsultatsiya davomiyligi (daqiqa).'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Bir martalik konsultatsiya narxi (so'm). enabled=True bo'lsa majburiy.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
