# Generated by Django 5.2.13 on 2026-08-05 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_doctorprofile_consultation_duration_min_and_more'),
        ('meetings', '0005_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot', to='meetings.consultation'),
        ),
    ]
