# Generated by Django 5.2.13 on 2026-08-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0019_slot_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', help_text="Moderatsiya: faqat approved bo'lsa marketplace'da ko'rinadi/booking ochiladi.", max_length=10),
        ),
    ]
