# Generated by Django 6.0.3 on 2026-04-14 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Avto generatsiya qilinadi (birinchi savoldan) yoki user yangilaydi",
                        max_length=200,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("uz", "O'zbek"),
                            ("uz-cyrl", "Ўзбек"),
                            ("ru", "Русский"),
                        ],
                        default="uz",
                        max_length=10,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DietDailyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("questions_count", models.PositiveIntegerField(default=0)),
                ("tokens_input", models.PositiveIntegerField(default=0)),
                ("tokens_output", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DietMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "image_key",
                    models.CharField(
                        blank=True,
                        help_text="DO Spaces key (ovqat rasmi bo'lsa)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Qo'shimcha ma'lumot: food_name, portion, grams, pieces, calories",
                        null=True,
                    ),
                ),
                ("tokens_input", models.PositiveIntegerField(default=0)),
                ("tokens_output", models.PositiveIntegerField(default=0)),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="Xatarli savol bloklangan bo'lsa True (guardrail)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="diet_ai.dietconversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DietRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule",
                    models.CharField(
                        help_text="Masalan: 'shakarsiz', 'kam tuz', 'glyuten-free'",
                        max_length=200,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Sabab (ixtiyoriy, bemorga ham ko'rsatiladi)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diet_restrictions_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_restrictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dietconversation",
            index=models.Index(
                fields=["user", "-updated_at"], name="diet_ai_die_user_id_619f91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dietdailyusage",
            index=models.Index(
                fields=["user", "-date"], name="diet_ai_die_user_id_b306ff_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dietdailyusage",
            unique_together={("user", "date")},
        ),
        migrations.AddIndex(
            model_name="dietmessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="diet_ai_die_convers_bf7496_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dietrestriction",
            index=models.Index(
                fields=["patient", "is_active"], name="diet_ai_die_patient_01d041_idx"
            ),
        ),
    ]
