# Generated by Django 6.0.3 on 2026-04-20 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diet_ai", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("food_name", models.CharField(max_length=200)),
                ("calories", models.PositiveIntegerField(default=0)),
                ("carbs_grams", models.PositiveIntegerField(default=0)),
                ("protein_grams", models.PositiveIntegerField(default=0)),
                ("fat_grams", models.PositiveIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Qo'lda"),
                            ("ai_photo", "AI rasmi"),
                            ("ai_text", "AI matn"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Agar AI confirm orqali yaratilgan bo'lsa",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="diet_ai.dietmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date"], name="diet_ai_die_user_id_4a5e05_idx"
                    ),
                    models.Index(
                        fields=["user", "date", "source"],
                        name="diet_ai_die_user_id_731956_idx",
                    ),
                ],
            },
        ),
    ]
