# Generated by Django 6.0.3 on 2026-04-23 06:08

from django.db import migrations, models


def backfill_image_key(apps, schema_editor):
    """Eski AI-photo DietEntry yozuvlari uchun image_key'ni user message'dan olib to'ldiradi."""
    DietEntry = apps.get_model("diet_ai", "DietEntry")
    DietMessage = apps.get_model("diet_ai", "DietMessage")

    ai_photo_entries = DietEntry.objects.filter(
        source="ai_photo", image_key__isnull=True, ai_message__isnull=False
    ).select_related("ai_message")

    for entry in ai_photo_entries:
        assistant_msg = entry.ai_message
        if not assistant_msg:
            continue
        user_msg = (
            DietMessage.objects.filter(
                conversation=assistant_msg.conversation,
                role="user",
                image_key__isnull=False,
                created_at__lt=assistant_msg.created_at,
            )
            .exclude(image_key="")
            .order_by("-created_at")
            .first()
        )
        if user_msg and user_msg.image_key:
            entry.image_key = user_msg.image_key
            entry.save(update_fields=["image_key"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("diet_ai", "0002_dietentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietentry",
            name="image_key",
            field=models.CharField(
                blank=True,
                help_text="Ovqat rasmi DO Spaces key (AI photo-dan yoki manual upload)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_image_key, noop_reverse),
    ]
