# Generated by Django 5.2.13 on 2026-05-04 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_ai', '0003_dietentry_image_key'),
        ('users', '0008_backfill_patient_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietconversation',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_conversations', to='users.patient'),
        ),
        migrations.AddField(
            model_name='dietdailyusage',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_usage', to='users.patient'),
        ),
        migrations.AddField(
            model_name='dietentry',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_entries', to='users.patient'),
        ),
        migrations.AddField(
            model_name='dietrestriction',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_restrictions', to='users.patient'),
        ),
    ]
