# Generated by Django 5.2.13 on 2026-05-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_ai', '0005_backfill_patient_profile'),
        ('doctors', '0010_backfill_doctorpatient_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietrestriction',
            name='doctor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_restrictions_set', to='doctors.doctorprofile'),
        ),
    ]
