# Generated by Django 5.2.13 on 2026-07-21 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_ai', '0007_backfill_doctor_profile'),
        ('users', '0009_alter_user_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dietentry',
            name='glycemic_load',
            field=models.CharField(blank=True, choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori')], help_text='AI baholagan glikemik yuk (diabet/surunkali kasallik nazorati)', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='dietentry',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('dinner', 'Kechki'), ('snack', 'Gazak')], help_text='Ovqatlanish mahali; berilmasa created_at soatidan aniqlanadi', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='DietProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('lose', 'Ozish'), ('gain', "Vazn yig'ish"), ('muscle', 'Muskul chiqarish'), ('condition', 'Kasallik nazorati'), ('maintain', "Sog'lom ovqatlanish")], default='maintain', max_length=12)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('pace_kg_week', models.DecimalField(blank=True, decimal_places=2, help_text='0.25 / 0.5 / 0.75, maks 1.0', max_digits=3, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', "O'tirib ishlash"), ('light', 'Yengil'), ('moderate', "O'rtacha"), ('high', 'Yuqori'), ('very_high', 'Juda yuqori')], default='light', max_length=10)),
                ('meals_per_day', models.CharField(choices=[('two', '2 mahal'), ('three', '3 mahal'), ('three_snack', '3 mahal + gazak'), ('four', '4 mahal'), ('five_plus', '5+')], default='three', max_length=12)),
                ('restrictions', models.JSONField(blank=True, default=list, help_text="['halal','vegetarian','lactose_free','gluten_free','nut_allergy',...]")),
                ('motivation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_profile', to='users.patient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diet_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
