# Generated by Django 5.2.13 on 2026-07-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_ai', '0008_dietentry_glycemic_load_dietentry_meal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietprofile',
            name='obstacles',
            field=models.JSONField(blank=True, default=list, help_text="Nima to'xtatadi: ['discipline','habits','support','schedule'] — AI ohangi"),
        ),
        migrations.AddField(
            model_name='dietprofile',
            name='outcomes',
            field=models.JSONField(blank=True, default=list, help_text="Nimaga erishmoq: ['healthy_eating','energy_mood','motivation_discipline','body_look'] — AI fokusi"),
        ),
        migrations.AddField(
            model_name='dietprofile',
            name='target_overrides',
            field=models.JSONField(blank=True, default=dict, help_text="Foydalanuvchi qo'lda tahriri: {calories,carbs_g,protein_g,fat_g} — clamp'lanadi (doctor ustun)"),
        ),
    ]
