# Generated by Django 5.2.13 on 2026-07-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_ai', '0009_dietprofile_obstacles_dietprofile_outcomes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietentry',
            name='ingredients',
            field=models.JSONField(blank=True, default=list, help_text='[{name, grams, calories, carbs_g, protein_g, fat_g}] — tahrirlanadi'),
        ),
        migrations.AddField(
            model_name='dietentry',
            name='portion_grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
