# Generated by Django 5.2.13 on 2026-06-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_scope', models.CharField(choices=[('patient', 'Patient app'), ('doctor', 'Doctor app')], max_length=10, unique=True)),
                ('latest_version', models.CharField(blank=True, help_text='Eng yangi versiya, masalan 1.4.2', max_length=20)),
                ('min_version', models.CharField(blank=True, help_text="Minimal qo'llab-quvvatlanadigan versiya — pastrog'i majburiy yangilanadi", max_length=20)),
                ('update_available', models.BooleanField(default=False, help_text="Yumshoq banner — 'yangilanish bor'")),
                ('force_update', models.BooleanField(default=False, help_text='Majburiy — eski versiyani bloklaydi')),
                ('title', models.JSONField(blank=True, default=dict, help_text='3 tilli sarlavha {uz,ru,cyr}')),
                ('message', models.JSONField(blank=True, default=dict, help_text='3 tilli matn {uz,ru,cyr}')),
                ('ios_url', models.URLField(blank=True, help_text='App Store havolasi (Yangilash tugmasi)')),
                ('android_url', models.URLField(blank=True, help_text='Play Store havolasi')),
                ('is_active', models.BooleanField(default=True, help_text="False → mobil hech qanday banner ko'rsatmaydi")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['app_scope'],
            },
        ),
    ]
